# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/
#   https://gohugo.io/configuration/languages/



languages:
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    pagination:
      path: page
    params:
      subtitle: Reference, Tutorials, and Explanations
      description: Site description in ...
    timeZone: Asia/Shanghai
    title: Jiashun Wang's Academic Homepage
    weight: 1

  zh:
    languageCode: zh-Hans
    languageName: 简体中文
    contentDir: content/zh
    pagination:
      path: page
    params:
      subtitle: Reference, Tutorials, and Explanations
      description: Site description in ...
    timeZone: Asia/Shanghai
    title: 王佳顺的学术主页
    weight: 2

